language: r

warnings_are_errors: true

sudo: false

virtualenv:
  - system_site_packages: true

env:
  global:
    - CRAN: http://cran.rstudio.com

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - python
    - python-setuptools
    - python-dev
    - python-numpy

before_install:
  - apt-get update -qq
  - easy_install -f http://biopython.org/DIST/ biopython

r_binary_packages:
  - testthat
  - shiny
  
r_github_packages:
  - jimhester/lintr

before_script: Rscript ./travis/travis_prep.R

bioc_packages:
  - muscle

script:
  - ./travis/travis_run_tests.sh
  - ./travis/travis_run_build.sh

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: FqrN7lDzvMI8BshrwJL1XUvpf0YzWzYnQEMVC/KM3VI75gZg8yf4jm8gWiE+OZjqIuJgjcH/I62n6HDkafctiNGkrE7qF8LiZJ8VvRjHUUto8/Fu1Tvza9h7bzgDd79C0zE7cY4z8jBsVE536snn+0XvBQ1hZVfvpduLJL8Z5G/cBwvS+GP62ESFMZ2BWA00+vfg4415jICO3TUyc8H1LXOT3gFB4hz0Bqomw9Qgg7msxy0xYuezhU7yX/PpwkgVhrNJNIyIz2UZgfL1d5CykW1IyzeVvS5nd6W6lyrv7iZvWw9Afc/i5dK4j2JfYeeOYaNIJ0uJB1JiDloO62zLiXoA4ukN+67D/+Mfzmy9Kd4HsiArtxEkE+OmuuDP9HJ+sZay7XKMjwnOQmzwPGFjb2plH4w4HnecrGoiBwRLvd3ITzyMjWKWKmUOmpjM78kdvdt3JsFTxP9LBg8EHKBLepKcOJuzlPrLZ1yEmRzYm4A6azLIvLAQ4b3xzw77IrePze7dLkuNs3NpQcp5+dH30Tfsz2sSMQnDTy9MC1D6TKJeGKk2zJAOWV4L8v2O5bVgaFxl1KIrnNj1dg55IIhE6DqdB/iR+VdonXxgSHOsoyQxicM+QqvyYf6d3QoBv+i8egXBfC3l7ic9m8dz/opNX29Ww3f8F5OaH7AWhcKy+3M=

branches:
  only:
    - master
    - dev
    - travis
